apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service

  template:
    metadata:
      labels:
        app: product-service

    spec:
      containers:
      - name: product-service

        image: 089089715847.dkr.ecr.eu-north-1.amazonaws.com/product-service:v1

        ports:
        - containerPort: 3002