apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: {{ .Values.productService.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: "{{ .Values.productService.image.repository }}:{{ .Values.productService.image.tag }}"
          ports:
            - containerPort: {{ .Values.productService.port }}