name: Build and Deploy Microservices

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-north-1
  EKS_CLUSTER_NAME: devops-eks-cluster
  ECR_REGISTRY: 805909320592.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  build-and-deploy:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authenticate to AWS using GitHub OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Verify AWS identity
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      # 4. Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 5. Set image tag
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 6. Build and push User Service
      - name: Build and push user-service
        run: |
          docker build \
            -t $ECR_REGISTRY/user-service:$IMAGE_TAG \
            ./user-services

          docker push \
            $ECR_REGISTRY/user-service:$IMAGE_TAG

      # 7. Build and push Product Service
      - name: Build and push product-service
        run: |
          docker build \
            -t $ECR_REGISTRY/product-service:$IMAGE_TAG \
            ./product-services

          docker push \
            $ECR_REGISTRY/product-service:$IMAGE_TAG

      # 8. Build and push Order Service
      - name: Build and push order-service
        run: |
          docker build \
            -t $ECR_REGISTRY/order-service:$IMAGE_TAG \
            ./order-services

          docker push \
            $ECR_REGISTRY/order-service:$IMAGE_TAG

      # 9. Configure kubectl for EKS
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER_NAME

      # 10. Verify Kubernetes connection
      - name: Check Kubernetes cluster
        run: |
           kubectl get deployments
           kubectl get pods

      # 11. Install Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4

      # 12. Deploy with Helm
      - name: Deploy microservices
        run: |
          helm upgrade --install micro-services ./helm/micro-services \
            --namespace default \
            --set userService.image.repository=$ECR_REGISTRY/user-service \
            --set userService.image.tag=$IMAGE_TAG \
            --set productService.image.repository=$ECR_REGISTRY/product-service \
            --set productService.image.tag=$IMAGE_TAG \
            --set orderService.image.repository=$ECR_REGISTRY/order-service \
            --set orderService.image.tag=$IMAGE_TAG

      # 13. Wait for deployments
      - name: Verify deployments
        run: |
          kubectl rollout status deployment/user-service --namespace default
          kubectl rollout status deployment/product-service --namespace default
          kubectl rollout status deployment/order-service --namespace default

      # 14. Show final status
      - name: Show Kubernetes resources
        run: |
          kubectl get pods
          kubectl get services
          kubectl get ingress